[graph]
targets = []
all-features = false
no-default-features = false

[licenses]
version = 2
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
    "CC0-1.0",
]
confidence-threshold = 0.8
copyleft = "deny"
allow-osi-fsf-free = "both"
default = "deny"

[[licenses.exceptions]]
allow = ["OpenSSL"]
name = "ring"

[bans]
multiple-versions = "warn"
wildcards = "deny"
highlight = "all"
workspace-default-features = "allow"
external-default-features = "allow"
allow = []

# Skip some multiple version checks for commonly problematic crates
skip = [
    { name = "windows-sys" },
    { name = "windows-targets" },
    { name = "windows_*" },
]

# Deny specific crates
deny = [
    { name = "openssl", reason = "Use rustls instead" },
    { name = "pcre2", reason = "Use regex instead" },
]

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []

[advisories]
version = 2
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
yanked = "deny"
ignore = []

[output]
feature-depth = 1